# SPDX-FileCopyrightText: © 2026 Logan Magee
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          check-latest: true
      - run: npm ci
      - run: npm run build

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          check-latest: true
      - run: npm ci
      - run: npm run fmt:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          check-latest: true
      - run: npm ci
      - run: npm run lint:ci

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          check-latest: true
      - run: npm ci
      - run: npm run test

  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: fsfe/reuse-action@v6
